spring.application.name=teamup_data_service
server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.datasource.url=jdbc:postgresql://localhost:5433/teamup_service
spring.datasource.username=postgres
spring.datasource.password=1111

spring.main.allow-circular-references=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true